# Generated by Django 3.2 on 2021-04-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoedata',
            name='image_url',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='shoedata',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
