# Generated by Django 3.2 on 2021-04-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jordan',
            name='description',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AddField(
            model_name='nike',
            name='description',
            field=models.CharField(default='N/A', max_length=300),
        ),
        migrations.AddField(
            model_name='puma',
            name='description',
            field=models.CharField(default='N/A', max_length=300),
        ),
    ]
