# Generated by Django 3.2 on 2021-04-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshoes', '0002_auto_20210419_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoedata',
            name='price',
            field=models.IntegerField(default='N/A'),
        ),
    ]
