# Generated by Django 3.2 on 2021-04-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshoes', '0003_alter_shoedata_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(default='N/A')),
                ('name', models.CharField(default='N/A', max_length=100)),
                ('price', models.IntegerField(default='N/A')),
            ],
        ),
        migrations.CreateModel(
            name='Puma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(default='N/A')),
                ('name', models.CharField(default='N/A', max_length=100)),
                ('price', models.IntegerField(default='N/A')),
            ],
        ),
        migrations.RenameModel(
            old_name='ShoeData',
            new_name='Jordan',
        ),
    ]
