# Generated by Django 3.2 on 2021-04-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshoes', '0004_auto_20210419_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jordan',
            name='price',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='nike',
            name='price',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='puma',
            name='price',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
